#!/usr/bin/env bash
# Generated by archive_site_mission_20260724.py for 62_Collins_Dr.
# Starts field logging in the background and Pure Pursuit in the foreground.
# Run from any directory; every path is resolved relative to this file.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PURE_PURSUIT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TRACTOR_RPI_DIR="$(cd "${PURE_PURSUIT_DIR}/.." && pwd)"

MISSION="${SCRIPT_DIR}/62_Collins_Dr_mission.txt"
VALIDATION="${SCRIPT_DIR}/62_Collins_Dr_mission_validation.json"
CONTROLLER="${PURE_PURSUIT_DIR}/pure_pursuit_controller_20260714.py"
LOGGER="${TRACTOR_RPI_DIR}/field_test_logger_20260717.py"
EXPECTED_SHA256="A17A34EE28531C39D62E0D77FD736B3442A4F86D82F92E89839DC91712234BF0"

for required in "${MISSION}" "${VALIDATION}" "${CONTROLLER}" "${LOGGER}"; do
    if [[ ! -f "${required}" ]]; then
        echo "ERROR: required file not found: ${required}"
        exit 1
    fi
done

if ! grep -Eq '"status"[[:space:]]*:[[:space:]]*"PASS"' "${VALIDATION}"; then
    echo "ERROR: validation report does not contain PASS: ${VALIDATION}"
    exit 1
fi

ACTUAL_SHA256="$(sha256sum "${MISSION}" | awk '{print $1}')"
if [[ "${ACTUAL_SHA256^^}" != "${EXPECTED_SHA256}" ]]; then
    echo "ERROR: mission SHA-256 does not match the archived validated mission."
    echo "Expected: ${EXPECTED_SHA256}"
    echo "Actual  : ${ACTUAL_SHA256^^}"
    exit 1
fi

LOGGER_PID=""
cleanup() {
    if [[ -n "${LOGGER_PID}" ]] && kill -0 "${LOGGER_PID}" 2>/dev/null; then
        echo ""
        echo "Stopping logger (PID ${LOGGER_PID})..."
        kill "${LOGGER_PID}"
        wait "${LOGGER_PID}" 2>/dev/null || true
        echo "Logger stopped."
    fi
}
trap cleanup EXIT

echo "========================================"
echo "  tractor2025 -- validated site mission"
echo "  $(date '+%Y-%m-%d %H:%M:%S')"
echo "  Site       : 62_Collins_Dr"
echo "  Mission    : 62_Collins_Dr_mission.txt"
echo "  SHA-256    : ${EXPECTED_SHA256}"
echo "  Speed cap  : 0.30 m/s (override only after approval)"
echo "========================================"

echo "Starting field data logger..."
python3 "${LOGGER}" &
LOGGER_PID=$!
echo "Logger running (PID ${LOGGER_PID})"
echo ""
echo "Waiting for RTK Fixed + valid heading."
echo "Keep the tractor in Manual or Pause until all checks are complete."
echo "Ctrl+C to abort at any time."
echo ""

python3 "${CONTROLLER}" \
    "${MISSION}" \
    --mode live \
    --ip 127.0.0.1 \
    --port 6004 \
    --max-speed 0.30 \
    "$@"
